source 'https://supermarket.chef.io'

cookbook 'apache2', '~> 8.14.1'
cookbook 'php', '~> 9.2.0'
cookbook 'apt', '~> 7.4.2'
cookbook 'composer', '~> 3.0.1'
cookbook 'packagecloud', '~> 1.0.1'
cookbook 'redisio', '~> 6.3.0'
cookbook 'imagemagick', '~> 0.2.3'
cookbook 'perl', '~> 8.0.1'
cookbook 'chrome', '~> 4.0.2'
cookbook 'nodejs', '~> 10.1.0'
cookbook 'chef-mailcatcher', '~> 0.2.1'